### ISSUE TITLE
Releases里面下载不了，能给个网盘链接吗？

### ISSUE THREAD

**Issue by Yrc030** [yixinin/leigodhelper#5]

**Comment by yixinin** [comment]
[https://res.cdn.office.net/assets/mail/file-icon/png/zip_16x16.png]leigodhelper (1).zip<https://1drv.ms/u/s!Au16wZWySmIxocojniz-fDJn2HWKqg>
________________________________
From: lll ***@***.***>
Sent: Sunday, February 11, 2024 10:36 AM
To: yixinin/leigodhelper ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [yixinin/leigodhelper] Releases里面下载不了，能给个网盘链接吗？ (Issue #5)


―
